/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IncidentIdRouteImport } from './routes/$incidentId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptInvitationInvitationIdRouteImport } from './routes/accept-invitation.$invitationId'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as StatusSlugIndexRouteImport } from './routes/status/$slug/index'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as StatusSlugVerifyRouteImport } from './routes/status/$slug/verify'
import { Route as StatusSlugIncidentIdRouteImport } from './routes/status/$slug/$incidentId'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedDashboardSubscribersRouteImport } from './routes/_authed/dashboard/subscribers'
import { Route as AuthedDashboardSettingsRouteImport } from './routes/_authed/dashboard/settings'
import { Route as AuthedDashboardStatusPagesIndexRouteImport } from './routes/_authed/dashboard/status-pages/index'
import { Route as AuthedDashboardMonitorsIndexRouteImport } from './routes/_authed/dashboard/monitors.index'
import { Route as AuthedDashboardIncidentsIndexRouteImport } from './routes/_authed/dashboard/incidents/index'
import { Route as AuthedDashboardStatusPagesPageIdRouteImport } from './routes/_authed/dashboard/status-pages/$pageId'
import { Route as AuthedDashboardMonitorsMonitorIdRouteImport } from './routes/_authed/dashboard/monitors.$monitorId'
import { Route as AuthedDashboardIncidentsIncidentIdRouteImport } from './routes/_authed/dashboard/incidents/$incidentId'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentIdRoute = IncidentIdRouteImport.update({
  id: '/$incidentId',
  path: '/$incidentId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationInvitationIdRoute =
  AcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const StatusSlugIndexRoute = StatusSlugIndexRouteImport.update({
  id: '/status/$slug/',
  path: '/status/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDashboardRoute,
} as any)
const StatusSlugVerifyRoute = StatusSlugVerifyRouteImport.update({
  id: '/status/$slug/verify',
  path: '/status/$slug/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusSlugIncidentIdRoute = StatusSlugIncidentIdRouteImport.update({
  id: '/status/$slug/$incidentId',
  path: '/status/$slug/$incidentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardSubscribersRoute =
  AuthedDashboardSubscribersRouteImport.update({
    id: '/subscribers',
    path: '/subscribers',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardSettingsRoute = AuthedDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedDashboardRoute,
} as any)
const AuthedDashboardStatusPagesIndexRoute =
  AuthedDashboardStatusPagesIndexRouteImport.update({
    id: '/status-pages/',
    path: '/status-pages/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardMonitorsIndexRoute =
  AuthedDashboardMonitorsIndexRouteImport.update({
    id: '/monitors/',
    path: '/monitors/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardIncidentsIndexRoute =
  AuthedDashboardIncidentsIndexRouteImport.update({
    id: '/incidents/',
    path: '/incidents/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardStatusPagesPageIdRoute =
  AuthedDashboardStatusPagesPageIdRouteImport.update({
    id: '/status-pages/$pageId',
    path: '/status-pages/$pageId',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardMonitorsMonitorIdRoute =
  AuthedDashboardMonitorsMonitorIdRouteImport.update({
    id: '/monitors/$monitorId',
    path: '/monitors/$monitorId',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardIncidentsIncidentIdRoute =
  AuthedDashboardIncidentsIncidentIdRouteImport.update({
    id: '/incidents/$incidentId',
    path: '/incidents/$incidentId',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$incidentId': typeof IncidentIdRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/dashboard': typeof AuthedDashboardRouteWithChildren
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/dashboard/settings': typeof AuthedDashboardSettingsRoute
  '/dashboard/subscribers': typeof AuthedDashboardSubscribersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/status/$slug/$incidentId': typeof StatusSlugIncidentIdRoute
  '/status/$slug/verify': typeof StatusSlugVerifyRoute
  '/dashboard/': typeof AuthedDashboardIndexRoute
  '/status/$slug/': typeof StatusSlugIndexRoute
  '/dashboard/incidents/$incidentId': typeof AuthedDashboardIncidentsIncidentIdRoute
  '/dashboard/monitors/$monitorId': typeof AuthedDashboardMonitorsMonitorIdRoute
  '/dashboard/status-pages/$pageId': typeof AuthedDashboardStatusPagesPageIdRoute
  '/dashboard/incidents/': typeof AuthedDashboardIncidentsIndexRoute
  '/dashboard/monitors/': typeof AuthedDashboardMonitorsIndexRoute
  '/dashboard/status-pages/': typeof AuthedDashboardStatusPagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$incidentId': typeof IncidentIdRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/dashboard/settings': typeof AuthedDashboardSettingsRoute
  '/dashboard/subscribers': typeof AuthedDashboardSubscribersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/status/$slug/$incidentId': typeof StatusSlugIncidentIdRoute
  '/status/$slug/verify': typeof StatusSlugVerifyRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/status/$slug': typeof StatusSlugIndexRoute
  '/dashboard/incidents/$incidentId': typeof AuthedDashboardIncidentsIncidentIdRoute
  '/dashboard/monitors/$monitorId': typeof AuthedDashboardMonitorsMonitorIdRoute
  '/dashboard/status-pages/$pageId': typeof AuthedDashboardStatusPagesPageIdRoute
  '/dashboard/incidents': typeof AuthedDashboardIncidentsIndexRoute
  '/dashboard/monitors': typeof AuthedDashboardMonitorsIndexRoute
  '/dashboard/status-pages': typeof AuthedDashboardStatusPagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$incidentId': typeof IncidentIdRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/_authed/dashboard': typeof AuthedDashboardRouteWithChildren
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/_authed/dashboard/settings': typeof AuthedDashboardSettingsRoute
  '/_authed/dashboard/subscribers': typeof AuthedDashboardSubscribersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/status/$slug/$incidentId': typeof StatusSlugIncidentIdRoute
  '/status/$slug/verify': typeof StatusSlugVerifyRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/status/$slug/': typeof StatusSlugIndexRoute
  '/_authed/dashboard/incidents/$incidentId': typeof AuthedDashboardIncidentsIncidentIdRoute
  '/_authed/dashboard/monitors/$monitorId': typeof AuthedDashboardMonitorsMonitorIdRoute
  '/_authed/dashboard/status-pages/$pageId': typeof AuthedDashboardStatusPagesPageIdRoute
  '/_authed/dashboard/incidents/': typeof AuthedDashboardIncidentsIndexRoute
  '/_authed/dashboard/monitors/': typeof AuthedDashboardMonitorsIndexRoute
  '/_authed/dashboard/status-pages/': typeof AuthedDashboardStatusPagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$incidentId'
    | '/login'
    | '/pricing'
    | '/dashboard'
    | '/accept-invitation/$invitationId'
    | '/dashboard/settings'
    | '/dashboard/subscribers'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/status/$slug/$incidentId'
    | '/status/$slug/verify'
    | '/dashboard/'
    | '/status/$slug/'
    | '/dashboard/incidents/$incidentId'
    | '/dashboard/monitors/$monitorId'
    | '/dashboard/status-pages/$pageId'
    | '/dashboard/incidents/'
    | '/dashboard/monitors/'
    | '/dashboard/status-pages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$incidentId'
    | '/login'
    | '/pricing'
    | '/accept-invitation/$invitationId'
    | '/dashboard/settings'
    | '/dashboard/subscribers'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/status/$slug/$incidentId'
    | '/status/$slug/verify'
    | '/dashboard'
    | '/status/$slug'
    | '/dashboard/incidents/$incidentId'
    | '/dashboard/monitors/$monitorId'
    | '/dashboard/status-pages/$pageId'
    | '/dashboard/incidents'
    | '/dashboard/monitors'
    | '/dashboard/status-pages'
  id:
    | '__root__'
    | '/'
    | '/$incidentId'
    | '/_authed'
    | '/login'
    | '/pricing'
    | '/_authed/dashboard'
    | '/accept-invitation/$invitationId'
    | '/_authed/dashboard/settings'
    | '/_authed/dashboard/subscribers'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/status/$slug/$incidentId'
    | '/status/$slug/verify'
    | '/_authed/dashboard/'
    | '/status/$slug/'
    | '/_authed/dashboard/incidents/$incidentId'
    | '/_authed/dashboard/monitors/$monitorId'
    | '/_authed/dashboard/status-pages/$pageId'
    | '/_authed/dashboard/incidents/'
    | '/_authed/dashboard/monitors/'
    | '/_authed/dashboard/status-pages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IncidentIdRoute: typeof IncidentIdRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  AcceptInvitationInvitationIdRoute: typeof AcceptInvitationInvitationIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  StatusSlugIncidentIdRoute: typeof StatusSlugIncidentIdRoute
  StatusSlugVerifyRoute: typeof StatusSlugVerifyRoute
  StatusSlugIndexRoute: typeof StatusSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$incidentId': {
      id: '/$incidentId'
      path: '/$incidentId'
      fullPath: '/$incidentId'
      preLoaderRoute: typeof IncidentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/status/$slug/': {
      id: '/status/$slug/'
      path: '/status/$slug'
      fullPath: '/status/$slug/'
      preLoaderRoute: typeof StatusSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/status/$slug/verify': {
      id: '/status/$slug/verify'
      path: '/status/$slug/verify'
      fullPath: '/status/$slug/verify'
      preLoaderRoute: typeof StatusSlugVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/$slug/$incidentId': {
      id: '/status/$slug/$incidentId'
      path: '/status/$slug/$incidentId'
      fullPath: '/status/$slug/$incidentId'
      preLoaderRoute: typeof StatusSlugIncidentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard/subscribers': {
      id: '/_authed/dashboard/subscribers'
      path: '/subscribers'
      fullPath: '/dashboard/subscribers'
      preLoaderRoute: typeof AuthedDashboardSubscribersRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/settings': {
      id: '/_authed/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthedDashboardSettingsRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/status-pages/': {
      id: '/_authed/dashboard/status-pages/'
      path: '/status-pages'
      fullPath: '/dashboard/status-pages/'
      preLoaderRoute: typeof AuthedDashboardStatusPagesIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/monitors/': {
      id: '/_authed/dashboard/monitors/'
      path: '/monitors'
      fullPath: '/dashboard/monitors/'
      preLoaderRoute: typeof AuthedDashboardMonitorsIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/incidents/': {
      id: '/_authed/dashboard/incidents/'
      path: '/incidents'
      fullPath: '/dashboard/incidents/'
      preLoaderRoute: typeof AuthedDashboardIncidentsIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/status-pages/$pageId': {
      id: '/_authed/dashboard/status-pages/$pageId'
      path: '/status-pages/$pageId'
      fullPath: '/dashboard/status-pages/$pageId'
      preLoaderRoute: typeof AuthedDashboardStatusPagesPageIdRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/monitors/$monitorId': {
      id: '/_authed/dashboard/monitors/$monitorId'
      path: '/monitors/$monitorId'
      fullPath: '/dashboard/monitors/$monitorId'
      preLoaderRoute: typeof AuthedDashboardMonitorsMonitorIdRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/incidents/$incidentId': {
      id: '/_authed/dashboard/incidents/$incidentId'
      path: '/incidents/$incidentId'
      fullPath: '/dashboard/incidents/$incidentId'
      preLoaderRoute: typeof AuthedDashboardIncidentsIncidentIdRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
  }
}

interface AuthedDashboardRouteChildren {
  AuthedDashboardSettingsRoute: typeof AuthedDashboardSettingsRoute
  AuthedDashboardSubscribersRoute: typeof AuthedDashboardSubscribersRoute
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
  AuthedDashboardIncidentsIncidentIdRoute: typeof AuthedDashboardIncidentsIncidentIdRoute
  AuthedDashboardMonitorsMonitorIdRoute: typeof AuthedDashboardMonitorsMonitorIdRoute
  AuthedDashboardStatusPagesPageIdRoute: typeof AuthedDashboardStatusPagesPageIdRoute
  AuthedDashboardIncidentsIndexRoute: typeof AuthedDashboardIncidentsIndexRoute
  AuthedDashboardMonitorsIndexRoute: typeof AuthedDashboardMonitorsIndexRoute
  AuthedDashboardStatusPagesIndexRoute: typeof AuthedDashboardStatusPagesIndexRoute
}

const AuthedDashboardRouteChildren: AuthedDashboardRouteChildren = {
  AuthedDashboardSettingsRoute: AuthedDashboardSettingsRoute,
  AuthedDashboardSubscribersRoute: AuthedDashboardSubscribersRoute,
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
  AuthedDashboardIncidentsIncidentIdRoute:
    AuthedDashboardIncidentsIncidentIdRoute,
  AuthedDashboardMonitorsMonitorIdRoute: AuthedDashboardMonitorsMonitorIdRoute,
  AuthedDashboardStatusPagesPageIdRoute: AuthedDashboardStatusPagesPageIdRoute,
  AuthedDashboardIncidentsIndexRoute: AuthedDashboardIncidentsIndexRoute,
  AuthedDashboardMonitorsIndexRoute: AuthedDashboardMonitorsIndexRoute,
  AuthedDashboardStatusPagesIndexRoute: AuthedDashboardStatusPagesIndexRoute,
}

const AuthedDashboardRouteWithChildren = AuthedDashboardRoute._addFileChildren(
  AuthedDashboardRouteChildren,
)

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IncidentIdRoute: IncidentIdRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  AcceptInvitationInvitationIdRoute: AcceptInvitationInvitationIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  StatusSlugIncidentIdRoute: StatusSlugIncidentIdRoute,
  StatusSlugVerifyRoute: StatusSlugVerifyRoute,
  StatusSlugIndexRoute: StatusSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
