/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IncidentIdRouteImport } from './routes/$incidentId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegistryIndexRouteImport } from './routes/registry/index'
import { Route as RegistrySlugRouteImport } from './routes/registry/$slug'
import { Route as AcceptInvitationInvitationIdRouteImport } from './routes/accept-invitation.$invitationId'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedAccountRouteImport } from './routes/_authed/account'
import { Route as StatusSlugIndexRouteImport } from './routes/status/$slug/index'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as StatusSlugVerifyRouteImport } from './routes/status/$slug/verify'
import { Route as StatusSlugIncidentIdRouteImport } from './routes/status/$slug/$incidentId'
import { Route as ApiV1SplatRouteImport } from './routes/api.v1.$'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedDashboardSubscribersRouteImport } from './routes/_authed/dashboard/subscribers'
import { Route as AuthedDashboardSettingsRouteImport } from './routes/_authed/dashboard/settings'
import { Route as AuthedDashboardNotificationsRouteImport } from './routes/_authed/dashboard/notifications'
import { Route as AuthedDashboardBillingRouteImport } from './routes/_authed/dashboard/billing'
import { Route as AuthedDashboardStatusPagesIndexRouteImport } from './routes/_authed/dashboard/status-pages/index'
import { Route as AuthedDashboardMonitorsIndexRouteImport } from './routes/_authed/dashboard/monitors/index'
import { Route as AuthedDashboardMaintenanceIndexRouteImport } from './routes/_authed/dashboard/maintenance/index'
import { Route as AuthedDashboardIncidentsIndexRouteImport } from './routes/_authed/dashboard/incidents/index'
import { Route as AuthedDashboardStatusPagesPageIdRouteImport } from './routes/_authed/dashboard/status-pages/$pageId'
import { Route as AuthedDashboardMonitorsNewRouteImport } from './routes/_authed/dashboard/monitors/new'
import { Route as AuthedDashboardIncidentsIncidentIdRouteImport } from './routes/_authed/dashboard/incidents/$incidentId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentIdRoute = IncidentIdRouteImport.update({
  id: '/$incidentId',
  path: '/$incidentId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryIndexRoute = RegistryIndexRouteImport.update({
  id: '/registry/',
  path: '/registry/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrySlugRoute = RegistrySlugRouteImport.update({
  id: '/registry/$slug',
  path: '/registry/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationInvitationIdRoute =
  AcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountRoute = AuthedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedRoute,
} as any)
const StatusSlugIndexRoute = StatusSlugIndexRouteImport.update({
  id: '/status/$slug/',
  path: '/status/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDashboardRoute,
} as any)
const StatusSlugVerifyRoute = StatusSlugVerifyRouteImport.update({
  id: '/status/$slug/verify',
  path: '/status/$slug/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusSlugIncidentIdRoute = StatusSlugIncidentIdRouteImport.update({
  id: '/status/$slug/$incidentId',
  path: '/status/$slug/$incidentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardSubscribersRoute =
  AuthedDashboardSubscribersRouteImport.update({
    id: '/subscribers',
    path: '/subscribers',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardSettingsRoute = AuthedDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedDashboardRoute,
} as any)
const AuthedDashboardNotificationsRoute =
  AuthedDashboardNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardBillingRoute = AuthedDashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthedDashboardRoute,
} as any)
const AuthedDashboardStatusPagesIndexRoute =
  AuthedDashboardStatusPagesIndexRouteImport.update({
    id: '/status-pages/',
    path: '/status-pages/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardMonitorsIndexRoute =
  AuthedDashboardMonitorsIndexRouteImport.update({
    id: '/monitors/',
    path: '/monitors/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardMaintenanceIndexRoute =
  AuthedDashboardMaintenanceIndexRouteImport.update({
    id: '/maintenance/',
    path: '/maintenance/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardIncidentsIndexRoute =
  AuthedDashboardIncidentsIndexRouteImport.update({
    id: '/incidents/',
    path: '/incidents/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardStatusPagesPageIdRoute =
  AuthedDashboardStatusPagesPageIdRouteImport.update({
    id: '/status-pages/$pageId',
    path: '/status-pages/$pageId',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardMonitorsNewRoute =
  AuthedDashboardMonitorsNewRouteImport.update({
    id: '/monitors/new',
    path: '/monitors/new',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardIncidentsIncidentIdRoute =
  AuthedDashboardIncidentsIncidentIdRouteImport.update({
    id: '/incidents/$incidentId',
    path: '/incidents/$incidentId',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$incidentId': typeof IncidentIdRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthedAccountRoute
  '/dashboard': typeof AuthedDashboardRouteWithChildren
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/registry/$slug': typeof RegistrySlugRoute
  '/registry/': typeof RegistryIndexRoute
  '/dashboard/billing': typeof AuthedDashboardBillingRoute
  '/dashboard/notifications': typeof AuthedDashboardNotificationsRoute
  '/dashboard/settings': typeof AuthedDashboardSettingsRoute
  '/dashboard/subscribers': typeof AuthedDashboardSubscribersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/status/$slug/$incidentId': typeof StatusSlugIncidentIdRoute
  '/status/$slug/verify': typeof StatusSlugVerifyRoute
  '/dashboard/': typeof AuthedDashboardIndexRoute
  '/status/$slug/': typeof StatusSlugIndexRoute
  '/dashboard/incidents/$incidentId': typeof AuthedDashboardIncidentsIncidentIdRoute
  '/dashboard/monitors/new': typeof AuthedDashboardMonitorsNewRoute
  '/dashboard/status-pages/$pageId': typeof AuthedDashboardStatusPagesPageIdRoute
  '/dashboard/incidents/': typeof AuthedDashboardIncidentsIndexRoute
  '/dashboard/maintenance/': typeof AuthedDashboardMaintenanceIndexRoute
  '/dashboard/monitors/': typeof AuthedDashboardMonitorsIndexRoute
  '/dashboard/status-pages/': typeof AuthedDashboardStatusPagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$incidentId': typeof IncidentIdRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthedAccountRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/registry/$slug': typeof RegistrySlugRoute
  '/registry': typeof RegistryIndexRoute
  '/dashboard/billing': typeof AuthedDashboardBillingRoute
  '/dashboard/notifications': typeof AuthedDashboardNotificationsRoute
  '/dashboard/settings': typeof AuthedDashboardSettingsRoute
  '/dashboard/subscribers': typeof AuthedDashboardSubscribersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/status/$slug/$incidentId': typeof StatusSlugIncidentIdRoute
  '/status/$slug/verify': typeof StatusSlugVerifyRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/status/$slug': typeof StatusSlugIndexRoute
  '/dashboard/incidents/$incidentId': typeof AuthedDashboardIncidentsIncidentIdRoute
  '/dashboard/monitors/new': typeof AuthedDashboardMonitorsNewRoute
  '/dashboard/status-pages/$pageId': typeof AuthedDashboardStatusPagesPageIdRoute
  '/dashboard/incidents': typeof AuthedDashboardIncidentsIndexRoute
  '/dashboard/maintenance': typeof AuthedDashboardMaintenanceIndexRoute
  '/dashboard/monitors': typeof AuthedDashboardMonitorsIndexRoute
  '/dashboard/status-pages': typeof AuthedDashboardStatusPagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$incidentId': typeof IncidentIdRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authed/account': typeof AuthedAccountRoute
  '/_authed/dashboard': typeof AuthedDashboardRouteWithChildren
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/registry/$slug': typeof RegistrySlugRoute
  '/registry/': typeof RegistryIndexRoute
  '/_authed/dashboard/billing': typeof AuthedDashboardBillingRoute
  '/_authed/dashboard/notifications': typeof AuthedDashboardNotificationsRoute
  '/_authed/dashboard/settings': typeof AuthedDashboardSettingsRoute
  '/_authed/dashboard/subscribers': typeof AuthedDashboardSubscribersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/status/$slug/$incidentId': typeof StatusSlugIncidentIdRoute
  '/status/$slug/verify': typeof StatusSlugVerifyRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/status/$slug/': typeof StatusSlugIndexRoute
  '/_authed/dashboard/incidents/$incidentId': typeof AuthedDashboardIncidentsIncidentIdRoute
  '/_authed/dashboard/monitors/new': typeof AuthedDashboardMonitorsNewRoute
  '/_authed/dashboard/status-pages/$pageId': typeof AuthedDashboardStatusPagesPageIdRoute
  '/_authed/dashboard/incidents/': typeof AuthedDashboardIncidentsIndexRoute
  '/_authed/dashboard/maintenance/': typeof AuthedDashboardMaintenanceIndexRoute
  '/_authed/dashboard/monitors/': typeof AuthedDashboardMonitorsIndexRoute
  '/_authed/dashboard/status-pages/': typeof AuthedDashboardStatusPagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$incidentId'
    | '/legal'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/account'
    | '/dashboard'
    | '/accept-invitation/$invitationId'
    | '/registry/$slug'
    | '/registry/'
    | '/dashboard/billing'
    | '/dashboard/notifications'
    | '/dashboard/settings'
    | '/dashboard/subscribers'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/v1/$'
    | '/status/$slug/$incidentId'
    | '/status/$slug/verify'
    | '/dashboard/'
    | '/status/$slug/'
    | '/dashboard/incidents/$incidentId'
    | '/dashboard/monitors/new'
    | '/dashboard/status-pages/$pageId'
    | '/dashboard/incidents/'
    | '/dashboard/maintenance/'
    | '/dashboard/monitors/'
    | '/dashboard/status-pages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$incidentId'
    | '/legal'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/account'
    | '/accept-invitation/$invitationId'
    | '/registry/$slug'
    | '/registry'
    | '/dashboard/billing'
    | '/dashboard/notifications'
    | '/dashboard/settings'
    | '/dashboard/subscribers'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/v1/$'
    | '/status/$slug/$incidentId'
    | '/status/$slug/verify'
    | '/dashboard'
    | '/status/$slug'
    | '/dashboard/incidents/$incidentId'
    | '/dashboard/monitors/new'
    | '/dashboard/status-pages/$pageId'
    | '/dashboard/incidents'
    | '/dashboard/maintenance'
    | '/dashboard/monitors'
    | '/dashboard/status-pages'
  id:
    | '__root__'
    | '/'
    | '/$incidentId'
    | '/_authed'
    | '/legal'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/_authed/account'
    | '/_authed/dashboard'
    | '/accept-invitation/$invitationId'
    | '/registry/$slug'
    | '/registry/'
    | '/_authed/dashboard/billing'
    | '/_authed/dashboard/notifications'
    | '/_authed/dashboard/settings'
    | '/_authed/dashboard/subscribers'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/v1/$'
    | '/status/$slug/$incidentId'
    | '/status/$slug/verify'
    | '/_authed/dashboard/'
    | '/status/$slug/'
    | '/_authed/dashboard/incidents/$incidentId'
    | '/_authed/dashboard/monitors/new'
    | '/_authed/dashboard/status-pages/$pageId'
    | '/_authed/dashboard/incidents/'
    | '/_authed/dashboard/maintenance/'
    | '/_authed/dashboard/monitors/'
    | '/_authed/dashboard/status-pages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IncidentIdRoute: typeof IncidentIdRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AcceptInvitationInvitationIdRoute: typeof AcceptInvitationInvitationIdRoute
  RegistrySlugRoute: typeof RegistrySlugRoute
  RegistryIndexRoute: typeof RegistryIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  StatusSlugIncidentIdRoute: typeof StatusSlugIncidentIdRoute
  StatusSlugVerifyRoute: typeof StatusSlugVerifyRoute
  StatusSlugIndexRoute: typeof StatusSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$incidentId': {
      id: '/$incidentId'
      path: '/$incidentId'
      fullPath: '/$incidentId'
      preLoaderRoute: typeof IncidentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry/': {
      id: '/registry/'
      path: '/registry'
      fullPath: '/registry/'
      preLoaderRoute: typeof RegistryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry/$slug': {
      id: '/registry/$slug'
      path: '/registry/$slug'
      fullPath: '/registry/$slug'
      preLoaderRoute: typeof RegistrySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/account': {
      id: '/_authed/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthedAccountRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/status/$slug/': {
      id: '/status/$slug/'
      path: '/status/$slug'
      fullPath: '/status/$slug/'
      preLoaderRoute: typeof StatusSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/status/$slug/verify': {
      id: '/status/$slug/verify'
      path: '/status/$slug/verify'
      fullPath: '/status/$slug/verify'
      preLoaderRoute: typeof StatusSlugVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/$slug/$incidentId': {
      id: '/status/$slug/$incidentId'
      path: '/status/$slug/$incidentId'
      fullPath: '/status/$slug/$incidentId'
      preLoaderRoute: typeof StatusSlugIncidentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard/subscribers': {
      id: '/_authed/dashboard/subscribers'
      path: '/subscribers'
      fullPath: '/dashboard/subscribers'
      preLoaderRoute: typeof AuthedDashboardSubscribersRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/settings': {
      id: '/_authed/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthedDashboardSettingsRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/notifications': {
      id: '/_authed/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof AuthedDashboardNotificationsRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/billing': {
      id: '/_authed/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof AuthedDashboardBillingRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/status-pages/': {
      id: '/_authed/dashboard/status-pages/'
      path: '/status-pages'
      fullPath: '/dashboard/status-pages/'
      preLoaderRoute: typeof AuthedDashboardStatusPagesIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/monitors/': {
      id: '/_authed/dashboard/monitors/'
      path: '/monitors'
      fullPath: '/dashboard/monitors/'
      preLoaderRoute: typeof AuthedDashboardMonitorsIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/maintenance/': {
      id: '/_authed/dashboard/maintenance/'
      path: '/maintenance'
      fullPath: '/dashboard/maintenance/'
      preLoaderRoute: typeof AuthedDashboardMaintenanceIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/incidents/': {
      id: '/_authed/dashboard/incidents/'
      path: '/incidents'
      fullPath: '/dashboard/incidents/'
      preLoaderRoute: typeof AuthedDashboardIncidentsIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/status-pages/$pageId': {
      id: '/_authed/dashboard/status-pages/$pageId'
      path: '/status-pages/$pageId'
      fullPath: '/dashboard/status-pages/$pageId'
      preLoaderRoute: typeof AuthedDashboardStatusPagesPageIdRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/monitors/new': {
      id: '/_authed/dashboard/monitors/new'
      path: '/monitors/new'
      fullPath: '/dashboard/monitors/new'
      preLoaderRoute: typeof AuthedDashboardMonitorsNewRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/incidents/$incidentId': {
      id: '/_authed/dashboard/incidents/$incidentId'
      path: '/incidents/$incidentId'
      fullPath: '/dashboard/incidents/$incidentId'
      preLoaderRoute: typeof AuthedDashboardIncidentsIncidentIdRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
  }
}

interface AuthedDashboardRouteChildren {
  AuthedDashboardBillingRoute: typeof AuthedDashboardBillingRoute
  AuthedDashboardNotificationsRoute: typeof AuthedDashboardNotificationsRoute
  AuthedDashboardSettingsRoute: typeof AuthedDashboardSettingsRoute
  AuthedDashboardSubscribersRoute: typeof AuthedDashboardSubscribersRoute
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
  AuthedDashboardIncidentsIncidentIdRoute: typeof AuthedDashboardIncidentsIncidentIdRoute
  AuthedDashboardMonitorsNewRoute: typeof AuthedDashboardMonitorsNewRoute
  AuthedDashboardStatusPagesPageIdRoute: typeof AuthedDashboardStatusPagesPageIdRoute
  AuthedDashboardIncidentsIndexRoute: typeof AuthedDashboardIncidentsIndexRoute
  AuthedDashboardMaintenanceIndexRoute: typeof AuthedDashboardMaintenanceIndexRoute
  AuthedDashboardMonitorsIndexRoute: typeof AuthedDashboardMonitorsIndexRoute
  AuthedDashboardStatusPagesIndexRoute: typeof AuthedDashboardStatusPagesIndexRoute
}

const AuthedDashboardRouteChildren: AuthedDashboardRouteChildren = {
  AuthedDashboardBillingRoute: AuthedDashboardBillingRoute,
  AuthedDashboardNotificationsRoute: AuthedDashboardNotificationsRoute,
  AuthedDashboardSettingsRoute: AuthedDashboardSettingsRoute,
  AuthedDashboardSubscribersRoute: AuthedDashboardSubscribersRoute,
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
  AuthedDashboardIncidentsIncidentIdRoute:
    AuthedDashboardIncidentsIncidentIdRoute,
  AuthedDashboardMonitorsNewRoute: AuthedDashboardMonitorsNewRoute,
  AuthedDashboardStatusPagesPageIdRoute: AuthedDashboardStatusPagesPageIdRoute,
  AuthedDashboardIncidentsIndexRoute: AuthedDashboardIncidentsIndexRoute,
  AuthedDashboardMaintenanceIndexRoute: AuthedDashboardMaintenanceIndexRoute,
  AuthedDashboardMonitorsIndexRoute: AuthedDashboardMonitorsIndexRoute,
  AuthedDashboardStatusPagesIndexRoute: AuthedDashboardStatusPagesIndexRoute,
}

const AuthedDashboardRouteWithChildren = AuthedDashboardRoute._addFileChildren(
  AuthedDashboardRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAccountRoute: typeof AuthedAccountRoute
  AuthedDashboardRoute: typeof AuthedDashboardRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAccountRoute: AuthedAccountRoute,
  AuthedDashboardRoute: AuthedDashboardRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IncidentIdRoute: IncidentIdRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AcceptInvitationInvitationIdRoute: AcceptInvitationInvitationIdRoute,
  RegistrySlugRoute: RegistrySlugRoute,
  RegistryIndexRoute: RegistryIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  StatusSlugIncidentIdRoute: StatusSlugIncidentIdRoute,
  StatusSlugVerifyRoute: StatusSlugVerifyRoute,
  StatusSlugIndexRoute: StatusSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
